services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    command:
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --providers.file.filename=/etc/traefik/dynamic.yml
    networks:
    - nmrxiv_net
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/ssl/nmrxiv.org/:/certs:ro
    - /etc/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro

  app:
    image: nfdi4chem/nmrxiv:app-latest
    depends_on:
    - pgsql
    - redis
    env_file:
    - ../.env
    environment:
    - SUPERVISOR_PHP_COMMAND="/usr/local/bin/php -d variables_order=EGPCS /var/www/html/artisan
      octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=80"
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY=${NO_PROXY}
    - http_proxy=${HTTP_PROXY}
    - https_proxy=${HTTPS_PROXY}
    - no_proxy=${NO_PROXY}
    - APP_URL=https://nmrxiv.org
    - NMRKIT_API_URL=http://nmrkit/latest/spectra/parse/url
    - TRUSTED_PROXIES="*"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD
      - curl
      - -f
      - http://localhost/octane-test
      timeout: 10s
    labels:
    - traefik.enable=true
    - traefik.http.routers.laravel.rule=Host(`nmrxiv.org`)
    - traefik.http.routers.laravel.entrypoints=websecure
    - traefik.http.routers.laravel.tls=true
    - traefik.http.services.laravel.loadbalancer.server.port=80
    networks:
    - nmrxiv_net
    restart: unless-stopped
    volumes:
    - app_storage:/var/www/html/storage
    - caddy_data:/data/caddy
    - ../.env:/var/www/html/.env


  worker:
    image: nfdi4chem/nmrxiv:worker-latest
    depends_on:
    - app
    - pgsql
    - redis
    env_file:
    - ../.env
    environment:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY=${NO_PROXY}
    - http_proxy=${HTTP_PROXY}
    - https_proxy=${HTTPS_PROXY}
    - no_proxy=${NO_PROXY}
    healthcheck:
      test: ["CMD", "pgrep", "-f", "artisan horizon"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
    - nmrxiv_net
    restart: unless-stopped
    volumes:
    - app_storage:/var/www/html/storage
    - ../.env:/var/www/html/.env

  nmrkit:
    image: nfdi4chem/nmrkit:latest
    pull_policy: always
    depends_on:
    - nmrkit_pgsql
    - nmrkit_redis
    env_file:
    - ../.env
    environment:
    - DB_HOST=nmrkit_pgsql
    - DB_PORT=5432
    - POSTGRES_DB=${NMRKIT_DB_DATABASE:-nmrkit}
    - POSTGRES_USER=${NMRKIT_DB_USERNAME:-nmrkit}
    - POSTGRES_PASSWORD=${NMRKIT_DB_PASSWORD:-password}
    - REDIS_HOST=nmrkit_redis
    - REDIS_PORT=6379
    labels:
    - traefik.enable=true
    - traefik.http.routers.nmrkit.rule=Host(`nmrkit.nmrxiv.org`)
    - traefik.http.routers.nmrkit.entrypoints=web
    - traefik.http.services.nmrkit.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/latest/registration/health"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
    - nmrxiv_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  nmr-load-save:
    image: nfdi4chem/nmr-cli:latest
    container_name: nmr-converter
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    networks:
    - nmrxiv_net
    volumes:
    - shared_data:/shared

  nmr-respredict:
    image: nfdi4chem/nmr-respredict:latest
    container_name: nmr-respredict
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    networks:
    - nmrxiv_net
    volumes:
    - shared_data:/shared

  nmrkit_pgsql:
    image: informaticsmatters/rdkit-cartridge-debian:latest
    env_file:
    - ../.env
    environment:
    - PG_VERSION=${NMRKIT_DB_VERSION:-15.4}
    - POSTGRES_DB=${NMRKIT_DB_DATABASE:-nmrkit}
    - POSTGRES_USER=${NMRKIT_DB_USERNAME:-nmrkit}
    - POSTGRES_PASSWORD=${NMRKIT_DB_PASSWORD:-password}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - pg_isready
      - -q
      - -d
      - ${NMRKIT_DB_DATABASE:-nmrkit}
      - -U
      - ${NMRKIT_DB_USERNAME:-nmrkit}
      timeout: 10s
    networks:
    - nmrxiv_net
    ports:
    - ${NMRKIT_DB_PORT:-5433}:5432
    restart: unless-stopped
    volumes:
    - nmrkit_pgsql_data:/var/lib/postgresql/data

  nmrkit_redis:
    image: redis:alpine
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 10s
    networks:
    - nmrxiv_net
    ports:
    - ${NMRKIT_REDIS_PORT:-6380}:6379
    restart: unless-stopped
    volumes:
    - nmrkit_redis_data:/data

  pgsql:
    image: informaticsmatters/rdkit-cartridge-debian:latest
    env_file:
    - ../.env
    environment:
    - PG_VERSION=${DB_VERSION:-15.4}
    - POSTGRES_DB=${DB_DATABASE:-nmrxiv}
    - POSTGRES_USER=${DB_USERNAME:-nmrxiv}
    - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - pg_isready
      - -q
      - -d
      - ${DB_DATABASE:-nmrxiv}
      - -U
      - ${DB_USERNAME:-nmrxiv}
      timeout: 10s
    networks:
    - nmrxiv_net
    ports:
    - ${DB_PORT:-5432}:5432
    restart: unless-stopped
    volumes:
    - pgsql_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 10s
    networks:
    - nmrxiv_net
    restart: unless-stopped
    volumes:
    - redis_data:/data

volumes:
  app_storage:
    driver: local
  caddy_data:
    driver: local
  pgsql_data:
    driver: local
  redis_data:
    driver: local
  nmrkit_pgsql_data:
    driver: local
  nmrkit_redis_data:
    driver: local
  shared_data:
    driver: local

networks:
  nmrxiv_net:
    driver: bridge
