name : Deploy to Dev

on:
  push:
    branches: [development]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: nmrxiv-dev
  GKE_ZONE: europe-west3-a
  DEPLOYMENT_NAME: nmrxiv-nmrxiv-app
  WORKER_DEPLOYMENT_NAME: nmrxiv-worker
  REPOSITORY_NAME: nmrxiv-dev
  APP_IMAGE: nmrxiv-app
  NGINX_IMAGE: nmrxiv-nginx

jobs:
  app-tests:
      runs-on: ubuntu-latest
      services:
        mysql:
          image: postgres:13
          env:
            POSTGRES_ALLOW_EMPTY_PASSWORD: yes
            POSTGRES_DATABASE: nmrxiv
          ports:
            - 5432
          #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      steps:
        - uses: actions/checkout@v2
        - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        - name: Install Composer Dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        - name: Install NPM Dependencies
          run: npm install
        - name: Generate key
          run: php artisan key:generate
        - name: Execute tests (Unit and Feature tests) using PHPUnit
          env:
            DB_PORT: ${{ job.services.postgres.ports[5432] }}
          run: php artisan test

  setup-build-publish-deploy:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    #needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |-
        gcloud auth configure-docker europe-west3-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.3.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build App Image
      run: |-
        docker build -f ./resources/ops/docker/app/app.dockerfile \
          --tag "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    - name: Build Nginx Image
      run: |-
        docker build -f ./resources/ops/docker/nginx/nginx.dockerfile \
          --tag "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$NGINX_IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish App Image to GCR
      run: |-
        docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest"

    - name: Publish Nginx Image to GCR
      run: |-
        docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$NGINX_IMAGE:latest"

    - name: Deploy
      run: |-
        kubectl rollout restart deployment/$DEPLOYMENT_NAME
        kubectl rollout restart deployment/$WORKER_DEPLOYMENT_NAME
        kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s
        kubectl get services -o wide