name : Deploy to Dev

on:
  push:
    branches: [cd-workflow]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: nmrxiv-dev
  GKE_ZONE: europe-west3-a
  DEPLOYMENT_NAME: nmrxiv-nmrxiv-app
  WORKER_DEPLOYMENT_NAME: nmrxiv-worker
  REPOSITORY_NAME: nmrxiv-dev
  APP_IMAGE: nmrxiv-app
  NGINX_IMAGE: nmrxiv-nginx

jobs:
  php-unit-test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nmrxiv
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install --ignore-platform-reqs
    - name: Prepare Laravel Application
      run: |
        php -r "file_exists('.env') || copy('.env.ci.dev', '.env');"

        echo AWS_ACCESS_KEY_ID='${{ secrets.development.AWS_ACCESS_KEY_ID }}' >> .env
        echo AWS_SECRET_ACCESS_KEY='${{ secrets.development.AWS_SECRET_ACCESS_KEY }}' >> .env
        echo MEILISEARCH_KEY='${{ secrets.development.MEILISEARCH_KEY }}' >> .env
        echo MEILISEARCH_PUBLICKEY='${{ secrets.development.MEILISEARCH_PUBLICKEY }}' >> .env

        php artisan key:generate
        php artisan migrate --seed
    - name: Install front-end dependencies
      run: |
        npm install
        npm run build
    - name: Run Test
      run: php artisan test --parallel


  setup-build-publish-deploy:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: php-unit-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |-
        gcloud auth configure-docker europe-west3-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.3.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build App Image
      run: |-
        docker build -f ./resources/ops/docker/app/app.dockerfile \
          --tag "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    - name: Build Nginx Image
      run: |-
        docker build -f ./resources/ops/docker/nginx/nginx.dockerfile \
          --tag "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$NGINX_IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish App Image to GCR
      run: |-
        docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest"

    - name: Publish Nginx Image to GCR
      run: |-
        docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$NGINX_IMAGE:latest"

    - name: Deploy
      run: |-
        kubectl rollout restart deployment/$DEPLOYMENT_NAME
        kubectl rollout restart deployment/$WORKER_DEPLOYMENT_NAME
        kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s
        kubectl get services -o wide