name: Release

on:
  push:
    branches:
      - development
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: nmrxiv


# name: Release

# on:
#   push:
#     branches:
#       - dev-helm-deploy

# env:
#   PACKAGE_NAME: nmrxiv

# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: google-github-actions/release-please-action@v3
#         id: release
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           release-type: php
#           package-name: nmrxiv
#           bump-minor-pre-major: true
#       - uses: actions/checkout@v3
#         # These if statements ensure that a publication only occurs when a new release is created
#         if: ${{ steps.release.outputs.release_created }}
#       - name: Update version number
#         run: |
#           echo "export default { version: 'v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}' };" > src/versionInfo.ts
#         if: ${{ steps.release.outputs.release_created }}
#       # - uses: actions/setup-node@v3
#       #   with:
#       #     php-version: ${{ env.NODE_VERSION }}
#       #     registry-url: 'https://registry.npmjs.org'
#       #   if: ${{ steps.release.outputs.release_created }}
#       # - run: npm install
#       #   if: ${{ steps.release.outputs.release_created }}
#       # - run: npm publish --access public
#       #   env:
#       #     NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
#       #   if: ${{ steps.release.outputs.release_created }}