name: Release Please 

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4.2.0
        with:
          release-type: php
          target-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          include-component-in-tag: false
          skip-github-release: false
          draft: false
          prerelease: false