apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-dev"
    nginx.ingress.kubernetes.io/proxy-body-size: 200M
    nginx.ingress.kubernetes.io/client-body-buffer-size: 200M
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  tls:
  - hosts:
      - nmrxiv.org
      - www.nmrxiv.org
    secretName: nmrxiv-app-prod-tls
  - hosts:
      - nmrium.nmrxiv.org
    secretName: nmrxiv-prod-nmrium-tls
  - hosts:
      - nmriumdev.nmrxiv.org
    secretName: nmrxiv-nmrium-tls
  - hosts:
      - msdev.nmrxiv.org
    secretName: nmrxiv-ms-tls
  - hosts:
      - dbdev.nmrxiv.org
    secretName: nmrxiv-dbdev-tls
  rules:
  - host: nmrxiv.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nmrxiv-nmrxiv-app
            port:
              number: 80
  - host: nmrium.nmrxiv.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nmrxiv-nmrium
            port:
              number: 80
  - host: ms.nmrxiv.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nmrxiv-meilisearch
            port:
              number: 7700
  - host: dbdev.nmrxiv.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nmrxiv-postgresql
            port:
              number: 5432